# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Dive - Container Image Analysis'
description: "Run Dive to analyze the container image efficiency"
author: "@martinheinz"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  image:
    description: "Image to analyze"
    required: true
  exit-zero:
    description: "Whether to exit with zero even when scan fails (still fails on error)"
    required: false
    default: "false"
  config:
    description: "Path to dive config file"
    required: false
    default: ${{ github.workspace }}/.dive-ci
  dive-tag:
    description: 'Tag of the wagoodman/dive image to use'
    required: false
    default: 'latest'
outputs:
  efficiency:
    description: 'Efficiency of the image'
  wasted-bytes:
    description: 'Number of wasted bytes'
  user-wasted-percent:
    description: 'Percentage of space waster'
runs:
  using: 'node12'
  main: 'dist/index.js'
